### ISSUE TITLE
Can't login with another language than English configured

### ISSUE THREAD

**Issue by alrick** [directus/app#1884]
If the user has another language than English configured, he will get a server error on login.

It seems that multiple page refresh allow to "bypass" the error but it happens again after a few navigation steps in the admin.

It's reproducible on the demo : 
1. Login
2. Change language to anything besides English
3. Logout and login again

The bug is present on latest build of the app. It was not present on 7.3.1, don't know in between as I've updated from this version.

**Comment by edenprojectde** [comment]
Related to #1878
It's the same Problem

It also happens after changing back to english. (for me at least)

**Comment by benhaynes** [comment]
I believe that @rijkvanzanten fixed this yesterday and it will be in the next release... but I'll let him confirm.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/app/commit/a53f9bb20c43725e85fae921d3cb5bea9fcbc2c6 🙂

**Comment by edenprojectde** [comment]
Is there an ETA when this will be pushed into the Suite? 
Or should i plan to make  a second instance of just the API on my Server?
I really dont want to go back some Versions because there are Features and functionalities i really need from 7.7.0 :')

**Comment by benhaynes** [comment]
I believe we'll have a release in a few hours, so all updates will be pushed to the Suite soon. :)

**Comment by rijkvanzanten** [comment]
@edenprojectde 

> when i should use the app vs the suite

The suite is no different from the app releases. Everytime we push a release of the app / api the suite gets updated too (suite = app master put in the api master for convenience)

**Comment by edenprojectde** [comment]
@rijkvanzanten 
![image](https://user-images.githubusercontent.com/6115966/62059553-d2198c80-b223-11e9-84db-d4e8bd3576c3.png)
I am still getting an error like this when i log out and back in again. Thats why i am asking :')

**Comment by edenprojectde** [comment]
Its fixed
