### ISSUE TITLE
Translations content doesn't show when viewed via relation

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/app#2589]
Setup:

- "Brand" Collection with a translation interface ("brand_transltions" collection)
- "Project" Collection with a many-to-many relation to the "brand" collection.

In "Brand" I can create my items with translations and they show up correctly.
Now, under "Project" I add my created brands. When I view them (in the modal) the translations don't show up.

Directus Version: 8.5.4, fresh install and translations interface setup according to the docs.

Here is a sql dump: https://www.dropbox.com/s/kmbjyynvgr72o76/translations-problem.sql?dl=0

**Comment by zerbfra** [comment]
Same bug here

**Comment by zerbfra** [comment]
Hi @benhaynes  the PR here from my repo should fix the behavior.
Some notes about it:

- I get the system language and I split the first part (I don't know if it is correct) so we can get the translation "slug"...for instance `en-US` becomes `en`
- If no translation found for the current system language fallback to the first one found
- The getItem api call should get all the data to get the translation fields (and not only the id)

A note on usage: in the relation field we need to specify the field to access. I modeled it with {{translation_field.field_to_display}} and the language is computed.

Let me know what you think

**Comment by zerbfra** [comment]
I made some refactor on it ;) using it right now and seems ok

**Comment by pgegenfurtner** [comment]
@zerbfra Great that you took some time to look into that! Thanks!

I tested your PR but it doesn't seem to do anything on my end.
Do I need to change my configuration?

**Comment by zerbfra** [comment]
> @zerbfra Great that you took some time to look into that! Thanks!
> 
> I tested your PR but it doesn't seem to do anything on my end.
> Do I need to change my configuration?

Yes, you should change in the "Project" entity, in the related field to "Brand" the  dropdown template as follows: `{{name_of_the_translation_field.field_to_display}}`

**Comment by pgegenfurtner** [comment]
It doesn't work for me. 

<img width="701" alt="Bildschirmfoto 2020-02-11 um 09 55 17" src="https://user-images.githubusercontent.com/19979167/74222399-b3a54b00-4cb4-11ea-9d33-20b999265ff4.png">

The translated fields don't show up, even though they are there and visible when I go directly in the brand collection

**Comment by zerbfra** [comment]
Did you get my latest version? Can you send here how did you setup the relation?

**Comment by pgegenfurtner** [comment]
Yes, commit 8475bfa5 ('refactor').

<img width="752" alt="Bildschirmfoto 2020-02-11 um 11 04 48" src="https://user-images.githubusercontent.com/19979167/74227230-531b0b80-4cbe-11ea-8a91-172b24e0bc8f.png">

This is the relation setup (many-to-many interface)

**Comment by zerbfra** [comment]
Send me your db dump and I'll check ;)

**Comment by pgegenfurtner** [comment]
You can download the dump here:
https://www.dropbox.com/s/505cya7y5vd875y/translations.sql?dl=0

Thanks!

**Comment by rarora-trip** [comment]
We seem to face same issue. I debugged and suspect that below check is reason https://github.com/directus/app/blob/master/src/interfaces/translation/input.vue#L139.
For getting child translations, we assume that it is new entity(the state this.newItem is not stored correctly for child items). Please check if this could be the potential reason for the issue

**Comment by zerbfra** [comment]
@rijkvanzanten are there some updates on this? My PR is still waiting and you have an additional explaination ;)

**Comment by lluishi93** [comment]
@rijkvanzanten Any news on this?

**Comment by rijkvanzanten** [comment]
No news. As for @zerbfra's PR, I'm still very torn on having the M2O be pre-programmed to show the translation like this. I know it's kinda the only way to fix it right now, but I'd rather keep them stick to their own responsibilities. The translations is a little bit of a weird case, as it's technically a one to many that you want to display as if it's a regular field with text, but based on the current language. We might have to move to a setup where the m2o can actually render the display component of the interface that's used for the related field, although that might be a little tricky combined with the display template where you can have multiple fields.

**Comment by pgegenfurtner** [comment]
Isn‘t there a temporary solution? 

I mean, it did work in the previous versions.
This breaks my whole setup and I can‘t update. But there are some nice new features I‘d like to use 😊

**Comment by rijkvanzanten** [comment]
> Isn‘t there a temporary solution?

Wish there was, that would've been merged and release if there were 😁 The open PR helps the preview value in the m2o dropdowns, but doesn't address the underlying problem (as listed in https://github.com/directus/app/issues/2643 too)

**Comment by nitishxp** [comment]
@rijkvanzanten any update over bug?

**Comment by stouch** [comment]
@rijkvanzanten is this going to be fixed in next version ? :)

**Comment by rijkvanzanten** [comment]
Yep!

**Comment by gianniskarmas** [comment]
Just bumped into this within a production site where I had to add new translations and got destroyed.
How long till this update gets implemented?

**Comment by cavaon-wayne** [comment]
I made a new PR for fixing this issue (https://github.com/directus/app/pull/2758).
It included some other coding for debounce, but if you guys like, you can copy my changes on the Translation Interface. Hope it works for you.

**Comment by darioseidl** [comment]
I'm seeing this bug too. The problem for us is that we were planning to only edit the related items "inline" which doesn't work.

E.g. we have questionnaire, questionnaire_answer, and questionnaire_answer_translations. The questionnaire_answer collection is hidden and the relation is set to allow to select existing answers. The answers and translations would be added and edited directly in the questionnaire form.

It seems the only workaround at the moment is to unhide the questionnaire_answer collection and to create/edit them in their own collection form. Then we also need to allow to select existing answers in the relation.

I'd be happy to test if there is a fix planned to be released.

**Comment by yuhe00** [comment]
We're also having this issue in 8.6.2. Would be great to see a fix for this soon!

**Comment by pgegenfurtner** [comment]
@yuhe00 It's fixed in the 8.7.0 release from yesterday

**Comment by benhaynes** [comment]
@rijkvanzanten @pgegenfurtner  — are we good to close this one then?

**Comment by pgegenfurtner** [comment]
All my translations work again. For me, the issue can be closed. Thanks!

**Comment by yuhe00** [comment]
Thanks for the update! Opening each item in the relation seems to be working now :)

However, translations are still not showing in the relation list:

![Screenshot_2020-05-19 Editing Item Topics](https://user-images.githubusercontent.com/305671/82332492-c3d07300-99e5-11ea-98fd-2e0e8e00c8ff.png)

**Comment by rijkvanzanten** [comment]
@yuhe00 Lets track that in a separate issue 🙂
